### ISSUE TITLE
Why overload require?

### ISSUE THREAD

**Issue by jedrichards** [css-modules/css-modulesify#28]
Thanks for the work on this! I'm really interested in CSS Modules, but confused about the decision to use the `require` function to load CSS files since this breaks universal JavaScript.

Surely a better solution would be something like,

```js
const css = require('css-modulesify')
const styles = css.load('./MyComponent.css')
```

Once bundled and running on the client any calls to `css.load()` will return the appropriate pre-processed styles object. When running on the server in a Node environment the same styles object is returned, but without attempting to load a CSS using `require()` causing errors or awkward source transformations and checks.

It'll work with ES6 too, since afaik imports are hoisted to the top of the file making `if (__CLIENT__)` checks difficult.

```
if (__CLIENT__) import styles from './MyComponent.css'
// breaks
```

Being able to require CSS files directly looks neat and all, and I see why it sort of makes more sense for the Webpack folks, but isn't one of the strengths of Browserify that it has a strong synergy with the Node environment and is well suited for universal JS projects?

Does this even make sense? Would it be better? Or have I misunderstood?

:-)

**Comment by jedrichards** [comment]
Oh, I've just found https://github.com/css-modules/css-modules/issues/13 ... now reading!

**Comment by geelen** [comment]
Yep, you can use https://github.com/css-modules/css-modules-require-hook for this!

**Comment by jedrichards** [comment]
Great, so it looks like I can use that to make `require('some.css')` work in my universal projects.

I'm still confused about the architectural decision to use `require` for loading CSS in the first place? After all its just a Node function with a reserved purpose of loading JS modules only. If the approach was something like my example above `css-modules-require-hook` wouldn't be needed at all. I'm keen to understand the underlying reason why ...

Anyway thanks for your time, no worries if you don't have time to explain I won't probe any further :-)

**Comment by joshwnj** [comment]
yeah @jedrichards I wondered about the use of `require` too. Some factors to consider:

- when doing a browserify build, using `require` gives you a neat way to also build your css file as a side effect (with browserify plugin). Not as easy if you are using something like `css.load(...)`

- we wanted to make it consistent with the webpack and jspm implementations. Css modules is more than just a library, it also has some opinions about workflow and how you'll use it. 

Of course, there's nothing at all stopping you from writing a normal function like you described, using the same code as the require-hook. It uses synchronous file IO (because that's how require works) but you can also use async IO if you wanted to extract css export tokens at runtime. 

Does that answer some of your questions?

**Comment by jedrichards** [comment]
Thanks for your time guys, yep its answers my questions!
