### ISSUE TITLE
Weird interaction with babel

### ISSUE THREAD

**Issue by bcomnes** [css-modules/css-modulesify#59]
Here's a fun bug:

```
var s = style = require('./style.css')
console.log(style)
```

When transforming this with the following options:

```
$ browserify -t [ babelify --presets [ es2015 react ] ] -p [ css-modulesify --after autoprefixer -o dist/main.css ] -o dist/bundle.

`style` is undefined when you try to use it.  Running:

```
$ browserify -p [ css-modulesify --after autoprefixer -o dist/main.css ] -o dist/bundle.
```

`style` is defined.  `s` works in both cases.

**Comment by joshwnj** [comment]
Hi @bcomnes I believe this is just a general babel thing, aside from css-modulesify. Eg:

https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=var%20a%20%3D%20b%20%3D%20'c'%0A

```
var a = b = 'c'
```

Gives `b is not defined`

It's because `a` has been declared as a `var` but `b` is treated as a global.
